version: 0.2

phases:
  install:

    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli
      - aws --version
     
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker logout
      - aws ssm get-parameter --name docker_password --with-decryption --query 'Parameters[0].Value' --output text > docker_password.txt
      - aws ssm get-parameter --name docker_username --with-decryption --query 'Parameters[0].Value' --output text > docker_username.txt
      - docker login -u $(cat docker_username.txt) -p $(cat docker_password.txt)

  build:
    commands:
      - echo Building Docker image...
      - docker build -t arithmetic-hello-world .

  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker tag arithmetic-hello-world palak21/arithmetic-hello-world
      - docker push palak21/arithmetic-hello-world
      - echo "Cleaning up..."
      - docker logout

artifacts:
  files:
    - '**/*'